- resources/views/search_results.blade.php
- vendor/composer/ClassLoader.php
- vendor/composer/InstalledVersions.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
- vendor/composer/installed.php
AI-131
Search Result Page Responsiveness in Mobile Phones and Ipad
> Version 3.2

- app/Http/Controllers/MainController.php
- resources/views/search_results.blade.php
This reverts commit 9f94fdd3d0b3a17f0c63d9e73afe6787f48ebef2.
> Revert "AI-198"

- app/Http/Controllers/MainController.php
- app/Http/Controllers/StockReservationController.php
- resources/views/deliveries_modal_content.blade.php
- resources/views/feedback_details_modal.blade.php
- resources/views/internal_transfer_modal_content.blade.php
- resources/views/item_profile.blade.php
- resources/views/layout.blade.php
- resources/views/material_issue.blade.php
- resources/views/material_issue_modal_content.blade.php
- resources/views/material_transfer.blade.php
- resources/views/material_transfer_for_manufacture.blade.php
- resources/views/order_replacement_modal_content.blade.php
- resources/views/picking_slip.blade.php
- resources/views/production_to_receive.blade.php
- resources/views/production_withdrawals_modal_content.blade.php
- resources/views/receipt.blade.php
- resources/views/replacement.blade.php
- resources/views/stock_reservation/list.blade.php
- resources/views/suggestion_box.blade.php
- resources/views/tbl_stock_ledger.blade.php
[AI-259](https://fumacoinc.atlassian.net/browse/AI-259) Incorrect stock ledger entries for Material transfer for return
[AI-258](https://fumacoinc.atlassian.net/browse/AI-258) In Feedback List - Painting, Able to enter negative value to 'Actual Qty Received'
[AI-257](https://fumacoinc.atlassian.net/browse/AI-257) In Item Profile, Balance qty of target warehouse is different from the actual qty of AthenaERP item profile page
[AI-256](https://fumacoinc.atlassian.net/browse/AI-256) In Internal Transfers List, Partially issuing removes item from the list of internal transfer
[AI-255](https://fumacoinc.atlassian.net/browse/AI-255) In Internal Transfers List, Clicking the item code still opens Item Profile and does not redirect to item profile page …
> Version 4.2

- app/Http/Controllers/MainController.php
- app/Http/Controllers/StockReservationController.php
- resources/views/item_profile.blade.php
- resources/views/layout.blade.php
- resources/views/material_transfer.blade.php
- resources/views/stock_reservation/list.blade.php
[AI-288](https://fumacoinc.atlassian.net/browse/AI-288) In Production WIthdrawals, Able to withdraw stocks more than the available qty using the 'Deduct from reserved' button
[AI-273](https://fumacoinc.atlassian.net/browse/AI-273) In Item Profile - Stock Reservations, Displayed reserved qty is 0 if the reserved qty is a float/decimal
[AI-272](https://fumacoinc.atlassian.net/browse/AI-272) In Production Withdrawals, Cannot withdraw from reserved stocks when there are available qty
[AI-271](https://fumacoinc.atlassian.net/browse/AI-271) In Item Profile - Stock Reservations, validity in days when updating a reservation is 0
[AI-270](https://fumacoinc.atlassian.net/browse/AI-270) Production Feedback, error upon clicking the "check" button …
> Version 4.3

- app/Http/Controllers/ConsignmentController.php
- app/Http/Controllers/MainController.php
- resources/views/consignment/beginning_inv_items.blade.php
- resources/views/consignment/index_consignment_supervisor.blade.php
- resources/views/consignment/promodiser_damage_report_form.blade.php
- resources/views/consignment/stock_transfer_form.blade.php
- resources/views/consignment/stock_transfers_list.blade.php
- resources/views/consignment/supervisor/tbl_audit_deliveries.blade.php
- resources/views/consignment/supervisor/tbl_audit_returns.blade.php
- resources/views/consignment/supervisor/tbl_audit_sales.blade.php
- resources/views/consignment/supervisor/tbl_sales_report.blade.php
- resources/views/consignment/supervisor/view_product_sold_list.blade.php
- resources/views/consignment/view_damaged_items_list.blade.php
- resources/views/layout.blade.php
- resources/views/search_results.blade.php
- routes/web.php
[AI-334](https://fumacoinc.atlassian.net/browse/AI-334) Incorrect Total Items Display in Beggining Inventory for Promodisers
[AI-330](https://fumacoinc.atlassian.net/browse/AI-330) Display Image in Add Item Modal for Promodiser
[AI-302](https://fumacoinc.atlassian.net/browse/AI-302) Sales Report per Store for Consignment Supervisor
[AI-299](https://fumacoinc.atlassian.net/browse/AI-299) Dashboard for Consignment Supervisor to display reports
[AI-283](https://fumacoinc.atlassian.net/browse/AI-283) Monthly Inventory Audit Report for consignment supervisor
> Version 5.2

- app/Http/Controllers/ConsignmentController.php
- resources/views/consignment/inventory_audit_form.blade.php
- resources/views/consignment/product_sold_form.blade.php
AI-359 - In Stock Transfers, Received item is not shown in Products Sold entry and Inventory Audit entry if item does not have beginning inventory entry
AI-346 - In Delivery List, Require input of price if item price is 0/null
> Version 5.3.1

- app/Http/Controllers/ConsignmentController.php
- app/Http/Controllers/MainController.php
- resources/views/consignment/index_consignment_supervisor.blade.php
- resources/views/consignment/tbl_submitted_inventory_audit.blade.php
- resources/views/consignment/view_inventory_audit_items.blade.php
- resources/views/index.blade.php
- routes/web.php
[AI-362](https://fumacoinc.atlassian.net/browse/AI-362) Display total sales in calendar per date for promodiser
[AI-361](https://fumacoinc.atlassian.net/browse/AI-361) Display Total Sales Amount in Inventory Audit History for "Promodisers"
[AI-322](https://fumacoinc.atlassian.net/browse/AI-322) Allow user's to have multiple user role in athenaERP
> Version 5.3.2

- app/Http/Controllers/ConsignmentController.php
- app/Http/Controllers/MainController.php
- config/laravel-webp.php
- resources/views/consignment/beginning_inv_items.blade.php
- resources/views/consignment/beginning_inv_list.blade.php
- resources/views/consignment/beginning_inventory.blade.php
- resources/views/consignment/beginning_inventory_list.blade.php
- resources/views/consignment/index_consignment_supervisor.blade.php
- resources/views/consignment/inventory_audit_form.blade.php
- resources/views/consignment/product_sold_form.blade.php
- resources/views/consignment/promodiser_damage_report_form.blade.php
- resources/views/consignment/promodiser_damaged_list.blade.php
- resources/views/consignment/promodiser_delivery_report.blade.php
- resources/views/consignment/stock_transfer_form.blade.php
- resources/views/consignment/stock_transfers_list.blade.php
- resources/views/consignment/supervisor/view_stock_adjustments.blade.php
[AI-379](https://fumacoinc.atlassian.net/browse/AI-379) Warning Message in Registration of Product Sold for input issues in promodiser
[AI-378](https://fumacoinc.atlassian.net/browse/AI-378) Warning Message in beginning inventory registration for input issue in promodiser
> Version 5.4.1

- app/Http/Controllers/ConsignmentController.php
- app/Http/Controllers/MainController.php
- app/LdapClasses/adLDAP.php
- resources/views/consignment/beginning_inv_items_list.blade.php
- resources/views/consignment/beginning_inventory.blade.php
- resources/views/consignment/beginning_inventory_list.blade.php
- resources/views/consignment/index_promodiser.blade.php
- resources/views/consignment/promodiser_delivery_report.blade.php
- resources/views/consignment/supervisor/view_stock_adjustments.blade.php
[AI-407](https://fumacoinc.atlassian.net/browse/AI-407) In Stock Transfers, cannot cancel STE
[AI-406](https://fumacoinc.atlassian.net/browse/AI-406) In Stock Adjustments, Unable to update price
[AI-400](https://fumacoinc.atlassian.net/browse/AI-400) Create "Create Beggining Inventory" in stock adjustment list
[AI-399](https://fumacoinc.atlassian.net/browse/AI-399) Success Notification Modal once "Received" is clicked for promodisers
[AI-396](https://fumacoinc.atlassian.net/browse/AI-396) Display pop up modal to promodiser user for pending beginning inventory
[AI-388](https://fumacoinc.atlassian.net/browse/AI-388) In beginning inventory, add option to add items upon approval for consignment supervisor
> Version 5.5.1

- app/Http/Controllers/ConsignmentController.php
- app/Http/Controllers/MainController.php
- resources/views/consignment/beginning_inv_items.blade.php
- resources/views/consignment/beginning_inv_items_list.blade.php
- resources/views/consignment/beginning_inventory.blade.php
- resources/views/consignment/beginning_inventory_list.blade.php
- resources/views/consignment/supervisor/view_stock_adjustments.blade.php
Added the ff columns to tabConsignment Beginning Inventory
- remarks => text, default: null
> Version 5.5.3

- app/Http/Controllers/ConsignmentController.php
- app/Http/Controllers/MainController.php
- resources/views/consignment/beginning_inv_items.blade.php
- resources/views/consignment/beginning_inv_items_list.blade.php
- resources/views/consignment/supervisor/tbl_inventory_audit_history.blade.php
- resources/views/consignment/supervisor/view_deliveries.blade.php
- resources/views/consignment/supervisor/view_inventory_audit.blade.php
[AI-452](https://fumacoinc.atlassian.net/browse/AI-452) In Inventory Report List, sort records based on audit period for Consignment Supervisor
[AI-451](https://fumacoinc.atlassian.net/browse/AI-451) In Delivery Report, unable to update price
[AI-450](https://fumacoinc.atlassian.net/browse/AI-450) In Beginning Inventory, Error message displays duplicate item codes
[AI-449](https://fumacoinc.atlassian.net/browse/AI-449) In Beginning Inventory, unable to submit beginning inventory entry
[AI-456](https://fumacoinc.atlassian.net/browse/AI-456) In Received Items List, add filter for status \(Received / To Receive\) for Consignment Supervisor
[AI-455](https://fumacoinc.atlassian.net/browse/AI-455) In Received Items List, add column for MREQ and Assigned Promodiser for Consignment Supervisor …
> Version 5.5.4

- app/Http/Controllers/ConsignmentController.php
- resources/views/consignment/supervisor/view_deliveries.blade.php
- resources/views/consignment/supervisor/view_inventory_audit_items.blade.php
Revised UI in Receive Item List and Inventory Report Page
> Revised UI

- app/Http/Controllers/ConsignmentController.php
- resources/views/consignment/index_consignment_supervisor.blade.php
- resources/views/consignment/supervisor/adjust_stocks.blade.php
- resources/views/consignment/supervisor/view_pending_to_receive.blade.php
- resources/views/consignment/supervisor/view_stock_adjustment_history.blade.php
- resources/views/consignment/supervisor/view_stock_adjustments.blade.php
- routes/web.php
[AI-466](https://fumacoinc.atlassian.net/browse/AI-466) Cutoff period error in Dashboard
[AI-468](https://fumacoinc.atlassian.net/browse/AI-468) Allow promodisers to edit beginning inventory
[AI-463](https://fumacoinc.atlassian.net/browse/AI-463) Stock Adjustment Form to input items for adjustment with logs
[AI-436](https://fumacoinc.atlassian.net/browse/AI-436) In consignment supervisor dashboard, display list of deliveries pending to receive
[AI-435](https://fumacoinc.atlassian.net/browse/AI-435) In delivery list, create page for delivery inquiry for promodiser
[AI-467](https://fumacoinc.atlassian.net/browse/AI-467) Standardize routes of beginning inventory for promodisers
Added the ff. Doctypes:
Consignment Stock Adjustment
warehouse => data
items => table, Consignment Stock Adjustment …
> Version 5.6

- app/Http/Controllers/ConsignmentController.php
- resources/views/brochure/preview_standard_brochure.blade.php
- resources/views/consignment/supervisor/tbl_inventory_audit_history.blade.php
- resources/views/consignment/supervisor/view_inventory_audit.blade.php
- resources/views/consignment/tbl_submitted_inventory_audit.blade.php
- resources/views/consignment/view_inventory_audit_items.blade.php
[AI-563](https://fumacoinc.atlassian.net/browse/AI-563) Promodiser Filter in Inventory Audit list for Consignment Supervisor
[AI-564](https://fumacoinc.atlassian.net/browse/AI-564) Display "Submitted by" in Inventory report history for promodiser
[AI-565](https://fumacoinc.atlassian.net/browse/AI-565) In inventory report history, include from 2022 inventory audit with ending in 2023 for year 2023 filter
[AI-566](https://fumacoinc.atlassian.net/browse/AI-566) Revise Image uploading form for Standard Product Brochure per Item
[AI-563]: https://fumacoinc.atlassian.net/browse/AI-563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AI-564]: https://fumacoinc.atlassian.net/browse/AI-564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> Version 7.1

- app/Http/Controllers/BrochureController.php
- resources/views/brochure/brochure_floater.blade.php
- resources/views/brochure/brochure_images.blade.php
- resources/views/brochure/multiple_brochure.blade.php
- resources/views/brochure/pdf.blade.php
- resources/views/brochure/preview_loop.blade.php
- resources/views/item_profile.blade.php
- resources/views/layout.blade.php
- routes/web.php
[AI-588](https://fumacoinc.atlassian.net/browse/AI-588) Menu to Add to brochure list
[AI-589](https://fumacoinc.atlassian.net/browse/AI-589) Page for list of brochures to generate
[AI-590](https://fumacoinc.atlassian.net/browse/AI-590) Print Preview for Multiple Item Brochures
[AI-591](https://fumacoinc.atlassian.net/browse/AI-591) Replace "Upload" to "Save" in uploading image modal
[AI-588]: https://fumacoinc.atlassian.net/browse/AI-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AI-589]: https://fumacoinc.atlassian.net/browse/AI-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AI-590]: https://fumacoinc.atlassian.net/browse/AI-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> Version 7.3

- app/Http/Controllers/BrochureController.php
- app/Http/Controllers/ConsignmentController.php
- app/Http/Controllers/ItemAttributeController.php
- app/Http/Controllers/LoginController.php
- app/Http/Controllers/MainController.php
- app/Http/Controllers/StockReservationController.php
- resources/views/brochure/brochure_floater.blade.php
- resources/views/brochure/form.blade.php
- resources/views/brochure/history.blade.php
- resources/views/brochure/multiple_brochure.blade.php
- resources/views/brochure/preview_loop.blade.php
- resources/views/brochure/print_preview.blade.php
- resources/views/consignment/index_promodiser.blade.php
- resources/views/consignment/promodiser_inventory_audit_list.blade.php
- resources/views/deliveries_modal_content.blade.php
- resources/views/internal_transfer_modal_content.blade.php
- resources/views/layout.blade.php
- resources/views/material_issue.blade.php
- resources/views/material_issue_modal_content.blade.php
- resources/views/material_transfer.blade.php
- resources/views/material_transfer_for_manufacture.blade.php
- resources/views/order_replacement_modal_content.blade.php
- resources/views/picking_slip.blade.php
- resources/views/production_withdrawals_modal_content.blade.php
- resources/views/replacement.blade.php
- resources/views/return_modal_content.blade.php
- resources/views/returns.blade.php
- resources/views/tbl_low_level_stocks.blade.php
- routes/web.php
- Added column in tabAthena Transactions
status => select, [Issued, Cancelled], default: Issued
> Version 7.4

- app/Http/Controllers/LoginController.php
- app/Http/Kernel.php
- app/Http/Middleware/SanitationMiddleware.php
- app/Providers/RouteServiceProvider.php
- resources/views/layout.blade.php
- routes/web.php
[AI-603](https://fumacoinc.atlassian.net/browse/AI-603) Sanitize user inputs to prevent XSS Attacks\(Athena.fumaco.org\)
[AI-604](https://fumacoinc.atlassian.net/browse/AI-604) Add RateLimiter to limit user requests
[AI-605](https://fumacoinc.atlassian.net/browse/AI-605) Warning message if user is logged out \(Session Expired\)
[AI-603]: https://fumacoinc.atlassian.net/browse/AI-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AI-604]: https://fumacoinc.atlassian.net/browse/AI-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AI-605]: https://fumacoinc.atlassian.net/browse/AI-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 7.5

- app/Http/Controllers/BrochureController.php
- app/Http/Controllers/ConsignmentController.php
- app/Http/Controllers/MainController.php
- app/Providers/RouteServiceProvider.php
- public/storage1/.gitignore
- resources/views/brochure/pdf.blade.php
- resources/views/consignment/index_consignment_supervisor.blade.php
- resources/views/consignment/supervisor/Import_tool/index.blade.php
- resources/views/consignment/supervisor/Import_tool/tbl.blade.php
- routes/web.php
[AI-610](https://fumacoinc.atlassian.net/browse/AI-610) In Withdrawal, unable to issue item if the source and target warehouse are the same
[AI-612](https://fumacoinc.atlassian.net/browse/AI-612) Create an import form for the Consignment Sales Report
[AI-613](https://fumacoinc.atlassian.net/browse/AI-613) Modal Preview for the Consignment Sales Report Import Form
[AI-614](https://fumacoinc.atlassian.net/browse/AI-614) Generate Sales Order in ERP for imported Sales Report
[AI-615](https://fumacoinc.atlassian.net/browse/AI-615) Excel Import Template for Consignment Sales Report
[AI-617](https://fumacoinc.atlassian.net/browse/AI-617) Form to assign a barcode to an item
[AI-610]: https://fumacoinc.atlassian.net/browse/AI-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> Version 7.6

- app/Http/Controllers/BrochureController.php
- app/Http/Controllers/MainController.php
- resources/views/deliveries_modal_content.blade.php
- resources/views/item_profile.blade.php
- resources/views/item_stock_level_bundled.blade.php
- resources/views/layout.blade.php
- resources/views/picking_slip.blade.php
- resources/views/search_results.blade.php
- resources/views/suggestion_box.blade.php
- routes/web.php
Added value 'Received' to column status on Stock Entry Detail
> Version 7.13

- app/Http/Controllers/ConsignmentController.php
- app/Http/Controllers/ItemController.php
- resources/views/item_attributes_list.blade.php
- resources/views/item_attributes_values_list.blade.php
- resources/views/item_profile.blade.php
- resources/views/update_item_form.blade.php
- routes/web.php
> Version 8.5
